//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSW.ServicioWebNet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServicioWebNet.WSOperaciones")]
    public interface WSOperaciones {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/loguinRequest", ReplyAction="http://ws/WSOperaciones/loguinResponse")]
        ClienteSW.ServicioWebNet.loguinResponse loguin(ClienteSW.ServicioWebNet.loguinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/loguinRequest", ReplyAction="http://ws/WSOperaciones/loguinResponse")]
        System.Threading.Tasks.Task<ClienteSW.ServicioWebNet.loguinResponse> loguinAsync(ClienteSW.ServicioWebNet.loguinRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/procesarPagoRequest", ReplyAction="http://ws/WSOperaciones/procesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.ServicioWebNet.procesarPagoResponse procesarPago(ClienteSW.ServicioWebNet.procesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperaciones/procesarPagoRequest", ReplyAction="http://ws/WSOperaciones/procesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteSW.ServicioWebNet.procesarPagoResponse> procesarPagoAsync(ClienteSW.ServicioWebNet.procesarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loguinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loguin", Namespace="http://ws/", Order=0)]
        public ClienteSW.ServicioWebNet.loguinRequestBody Body;
        
        public loguinRequest() {
        }
        
        public loguinRequest(ClienteSW.ServicioWebNet.loguinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loguinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pasword;
        
        public loguinRequestBody() {
        }
        
        public loguinRequestBody(string usario, string pasword) {
            this.usario = usario;
            this.pasword = pasword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loguinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loguinResponse", Namespace="http://ws/", Order=0)]
        public ClienteSW.ServicioWebNet.loguinResponseBody Body;
        
        public loguinResponse() {
        }
        
        public loguinResponse(ClienteSW.ServicioWebNet.loguinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loguinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public loguinResponseBody() {
        }
        
        public loguinResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarPago", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class procesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int deuda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pago;
        
        public procesarPagoRequest() {
        }
        
        public procesarPagoRequest(int deuda, int pago) {
            this.deuda = deuda;
            this.pago = pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarPagoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class procesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public procesarPagoResponse() {
        }
        
        public procesarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOperacionesChannel : ClienteSW.ServicioWebNet.WSOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOperacionesClient : System.ServiceModel.ClientBase<ClienteSW.ServicioWebNet.WSOperaciones>, ClienteSW.ServicioWebNet.WSOperaciones {
        
        public WSOperacionesClient() {
        }
        
        public WSOperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.ServicioWebNet.loguinResponse ClienteSW.ServicioWebNet.WSOperaciones.loguin(ClienteSW.ServicioWebNet.loguinRequest request) {
            return base.Channel.loguin(request);
        }
        
        public bool loguin(string usario, string pasword) {
            ClienteSW.ServicioWebNet.loguinRequest inValue = new ClienteSW.ServicioWebNet.loguinRequest();
            inValue.Body = new ClienteSW.ServicioWebNet.loguinRequestBody();
            inValue.Body.usario = usario;
            inValue.Body.pasword = pasword;
            ClienteSW.ServicioWebNet.loguinResponse retVal = ((ClienteSW.ServicioWebNet.WSOperaciones)(this)).loguin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.ServicioWebNet.loguinResponse> ClienteSW.ServicioWebNet.WSOperaciones.loguinAsync(ClienteSW.ServicioWebNet.loguinRequest request) {
            return base.Channel.loguinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.ServicioWebNet.loguinResponse> loguinAsync(string usario, string pasword) {
            ClienteSW.ServicioWebNet.loguinRequest inValue = new ClienteSW.ServicioWebNet.loguinRequest();
            inValue.Body = new ClienteSW.ServicioWebNet.loguinRequestBody();
            inValue.Body.usario = usario;
            inValue.Body.pasword = pasword;
            return ((ClienteSW.ServicioWebNet.WSOperaciones)(this)).loguinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.ServicioWebNet.procesarPagoResponse ClienteSW.ServicioWebNet.WSOperaciones.procesarPago(ClienteSW.ServicioWebNet.procesarPagoRequest request) {
            return base.Channel.procesarPago(request);
        }
        
        public int procesarPago(int deuda, int pago) {
            ClienteSW.ServicioWebNet.procesarPagoRequest inValue = new ClienteSW.ServicioWebNet.procesarPagoRequest();
            inValue.deuda = deuda;
            inValue.pago = pago;
            ClienteSW.ServicioWebNet.procesarPagoResponse retVal = ((ClienteSW.ServicioWebNet.WSOperaciones)(this)).procesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.ServicioWebNet.procesarPagoResponse> ClienteSW.ServicioWebNet.WSOperaciones.procesarPagoAsync(ClienteSW.ServicioWebNet.procesarPagoRequest request) {
            return base.Channel.procesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.ServicioWebNet.procesarPagoResponse> procesarPagoAsync(int deuda, int pago) {
            ClienteSW.ServicioWebNet.procesarPagoRequest inValue = new ClienteSW.ServicioWebNet.procesarPagoRequest();
            inValue.deuda = deuda;
            inValue.pago = pago;
            return ((ClienteSW.ServicioWebNet.WSOperaciones)(this)).procesarPagoAsync(inValue);
        }
    }
}
